# Generated by Django 5.2.17 on 2026-10-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
