# Generated by Django 5.2.17 on 2026-10-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_rename_update_at_entreprise_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('attribuee', 'Attribuée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='publiee', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expeditions', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
